export const GET_ADVERTS_PENDING = 'GET_ADVERTS_PENDING';
export const GET_ADVERTS_SUCCESS = 'GET_ADVERTS_SUCCESS';
export const GET_ADVERTS_FAIL = 'GET_ADVERTS_FAIL';
export const GET_ADVERT_ONE_SUCCESS = 'GET_ADVERT_ONE_SUCCESS';
export const ADD_FAVOURITE_ADVERT = 'ADD_FAVOURITE_ADVERT';
export const REMOVE_FAVOURITE_ADVERT = 'REMOVE_FAVOURITE_ADVERT';
export const GET_ADVERTS_FILTER_SUCCESS = 'GET_ADVERTS_FILTER_SUCCESS';
